# Generated by Django 3.1.7 on 2021-04-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_bookedplots_is_exited'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicleentry',
        ),
        migrations.DeleteModel(
            name='Vehicleexit',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='space',
            new_name='complaint_type',
        ),
        migrations.RenameField(
            model_name='complaints',
            old_name='contactno',
            new_name='contact_no',
        ),
    ]
